---
output: 
  html_document:
      keep_md: true
editor_options: 
  chunk_output_type: console
---

<!-- README.md is generated from README.Rmd. Please edit that file -->


## eco-das XIII stoichiometry

## Files

* `get_nars_links.R` - makes `nars_data_table.csv` spreadsheet, with an overview of the NARS data and file download links. 
* `data-download.Rmd` - download or read in files from NARS data and example map
* `wetlands.Rmd` - read in data from wetland 2011 survey

## Data Overview

NARS Surveys:

1. Lakes (2007)
1. Lakes (2012)
1. Streams (2004-2005)
1. Rivers and Streams (2008-2009)
1. Wetlands (2011)
1. Coastal (1999-2001, 2005-2006)
1. Coastal (2010)

Notes on outcome and driver variables of interest

**Wetlands**

* Water Chemistry - UID, DATE_COL, SITE_ID, TN, TN_USEABILITY, TP, TP_USEABILITY
* Soil Chemistry - UID, SITE_ID, DATE_COL, TOT_CARBON, TOT_CARBON_FLAG, TOT NITROGEN, TOT_NITROGEN_FLAG
* Landscape Data - metrics within 100, 200, 500 or 1000m buffers. NLCD 2001 and 2006 but not 2010. 

TN is in mg N/L
TP is in ug P/L

**Rivers 2008-2009**

* Water Chemistry - UID, SITE_ID, DATE_COL, DOC, DOC_ALERT, NTL, NTL_ALERT, PTL, PTL_ALERT

**Lakes 2012**



